### ISSUE TITLE
Support for Puma 5

### ISSUE THREAD

**Issue by Samsinite** [puma/puma-heroku#13]
Hi, love this gem, makes it easy to reliably configure puma for Heroku. But, I saw that a new version of puma was released and was wondering if this gem could be updated to support Puma 5. If there is anything I could do to contribute let me know, but I'm not certain how changes in puma 5 would affect this gem, and any insight would be helpful.

**Comment by nateberkopec** [comment]
We're sunsetting this gem. I'll update the readme.

Puma 5 now uses the same approach as this gem for setting thread count and worker count - you can set them via environment variables just like this gem allowed you to: https://github.com/puma/puma/blob/038a0d9da95a58d128bbbd76ebaacacd184e47e2/lib/puma/configuration.rb#L181

Puma 5 also uses `preload_app!` automatically now if you're using more than 1 worker: https://github.com/puma/puma/blob/038a0d9da95a58d128bbbd76ebaacacd184e47e2/lib/puma/configuration.rb#L143

To migrate, the only thing you need to do is change your Procfile to: `web: bundle exec puma -p ${PORT:-3000}`, because we don't automatically change the PORT setting, and if you're using Rails 5.1 or less, add back in the config regarding before_fork and on_worker_boot: https://github.com/puma/puma-heroku/blob/63a49eabf9288031439490bc168baa3e3c7c93d5/lib/puma/plugin/heroku.rb#L16

@schneems double check me on that port setting bit, is that correct?

**Comment by nateberkopec** [comment]
I'm starting to wonder whether or not setting Puma's port to `ENV['PORT']` should've been done in Puma 5. 

We generally encourage people to use the `puma` launcher rather than `rails server`. If you use `rails server`, the port gets set to 3000, but if you use `bundle exec puma` it will get set to 9292.

**Comment by nateberkopec** [comment]
Worse comes to worse we can update this gem to do nothing except port to ENV['port'] and warn people it will be retired in Puma 6.

**Comment by nateberkopec** [comment]
Done, v2 of this gem has been released. It will probably be the final release.

**Comment by Samsinite** [comment]
Sounds great, thanks for the detailed notes, look forward to upgrading an app!
